SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH,CAR_ID,COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  
WHERE CAR_ID IN (SELECT CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
				  WHERE START_DATE BETWEEN TO_DATE('2022-08-01','YYYY-MM-DD') AND TO_DATE('2022-10-31','YYYY-MM-DD')
				  GROUP BY CAR_ID
				 HAVING COUNT(CAR_ID)>=5)
  AND START_DATE BETWEEN TO_DATE('2022-08-01','YYYY-MM-DD') AND TO_DATE('2022-10-31','YYYY-MM-DD')               
GROUP BY CAR_ID,EXTRACT(MONTH FROM START_DATE)
HAVING COUNT(*) <> 0
ORDER BY 1,2 DESC;
	 -- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- 특정 월의 총 대여 횟수가 0인 경우에는 결과에서 제외해주세요.
-- 를 잘못 이해해서 오래걸렸다(0인경우에는 해당 차량 기록을 전부 결과에서 제외하라는 줄 알았음)