SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
  FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID=AO.ANIMAL_ID
 WHERE SEX_UPON_INTAKE LIKE 'Intact%' AND SEX_UPON_OUTCOME NOT LIKE 'Intact%'
 ORDER BY AO.ANIMAL_ID;
-- 보호소에서 중성화한 동물